# Generated by Django 4.0.1 on 2022-01-20 13:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_remove_task_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.CharField(blank=True, max_length=2000, null=True, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='Полное описание'),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Краткое описание'),
        ),
    ]
