# Generated by Django 4.0.1 on 2022-01-30 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_project'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Проект', 'verbose_name_plural': 'Проекты'},
        ),
        migrations.AlterModelTable(
            name='project',
            table='Projects',
        ),
    ]
