# Generated by Django 4.0.1 on 2022-01-31 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_task_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='updated_at',
            new_name='closed_at',
        ),
    ]
