# Generated by Django 4.0.1 on 2022-02-21 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0012_alter_project_users'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'permissions': [('can_add_users_to_project', 'Может добавлять пользователей в проект')], 'verbose_name': 'Проект', 'verbose_name_plural': 'Проекты'},
        ),
    ]
